export default {
  login: "fabpot",
  id: 47313,
  node_id: "MDQ6VXNlcjQ3MzEz",
  avatar_url: "https://avatars.githubusercontent.com/u/47313?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/fabpot",
  html_url: "https://github.com/fabpot",
  followers_url: "https://api.github.com/users/fabpot/followers",
  following_url: "https://api.github.com/users/fabpot/following{/other_user}",
  gists_url: "https://api.github.com/users/fabpot/gists{/gist_id}",
  starred_url: "https://api.github.com/users/fabpot/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/fabpot/subscriptions",
  organizations_url: "https://api.github.com/users/fabpot/orgs",
  repos_url: "https://api.github.com/users/fabpot/repos",
  events_url: "https://api.github.com/users/fabpot/events{/privacy}",
  received_events_url: "https://api.github.com/users/fabpot/received_events",
  type: "User",
  site_admin: false,
  name: "Fabien Potencier",
  company: "Symfony/Blackfire",
  blog: "http://fabien.potencier.org/",
  location: "Lille, France",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: "fabpot",
  public_repos: 55,
  public_gists: 12,
  followers: 11297,
  following: 0,
  created_at: "2009-01-17T13:42:51Z",
  updated_at: "2021-03-17T08:24:03Z",
};
